5afe/safe-relay-service

config/settings/base.py
requirements.txt
safe_relay_service/gas_station/gas_station.py
safe_relay_service/gas_station/tests/test_gas_station.py
safe_relay_service/safe/contracts.py
safe_relay_service/safe/models.py
safe_relay_service/safe/serializers.py
safe_relay_service/safe/tasks.py
safe_relay_service/safe/tests/test_tasks.py
safe_relay_service/safe/views.py
safe_relay_service/version.py

Small fixes and increase logging

Release v0.6.0

---

requirements.txt
safe_relay_service/gas_station/gas_station.py
safe_relay_service/relay/models.py
safe_relay_service/relay/serializers.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/relay/views.py

- Increment gas_prices by 1 wei on GasStation
- Return nonce on estimate gas endpoint

Merge develop

---

config/settings/base.py
requirements.txt
safe_relay_service/relay/models.py
safe_relay_service/relay/relay_service.py
safe_relay_service/relay/tasks.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/relay/views.py
safe_relay_service/tokens/exchanges.py
safe_relay_service/tokens/management/commands/update_tokens.py
safe_relay_service/tokens/models.py
safe_relay_service/tokens/tests/test_exchanges.py
safe_relay_service/tokens/token_repository.py
safe_relay_service/version.py

- Fix problems with nonces sending txs

Set version 2.3.4

---

requirements.txt
safe_relay_service/version.py

Fix problem with hex formatting for gas estimation

Set version 2.4.2

---

requirements.txt
safe_relay_service/version.py

Fix problem estimating ERC20 gas payments

 Set version 2.4.4

---

requirements.txt
safe_relay_service/tokens/views.py
safe_relay_service/version.py

- Fix problem with parity estimation
- Sort tokens by relevance and then name
- Update Django to 2.1.7 (Fix CVE-2019-6975)

 Set version 2.7.2

---

requirements.txt
safe_relay_service/gas_station/gas_station.py
safe_relay_service/relay/models.py
safe_relay_service/relay/repositories/redis_repository.py
safe_relay_service/relay/serializers.py
safe_relay_service/relay/services/funding_service.py
safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tasks.py
safe_relay_service/relay/tests/inherited/test_ethereum_client.py
safe_relay_service/relay/tests/inherited/test_ethereum_service.py
safe_relay_service/relay/tests/test_safe_creation_service.py
safe_relay_service/relay/tests/test_tasks.py
safe_relay_service/relay/tests/test_transaction_service.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/relay/tests/test_views_v2.py
safe_relay_service/relay/views.py
safe_relay_service/tokens/management/commands/add_token.py

Refactor safe txs

---

.travis.yml
README.md
docker/web/Dockerfile
docs/docker_ec2.rst
requirements-dev.txt
requirements-test.txt
requirements.txt
safe_relay_service/gas_station/gas_station.py
safe_relay_service/relay/management/commands/test_relay_server.py
safe_relay_service/relay/models.py
safe_relay_service/relay/serializers.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tests/test_funding_service.py
safe_relay_service/relay/views.py
safe_relay_service/version.py

- Refactor relay server testing
- Test sending multiple txs at same time
- Update python to 3.7
- Update dependencies
- Remove deprecated chainId
- Fix typo on SafeCreation2 model

 Set version v3.2.0

---

safe_relay_service/tokens/exchanges.py
safe_relay_service/tokens/models.py
safe_relay_service/tokens/tests/test_exchanges.py

Update DutchX price oracle

---

safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/tests/test_safe_creation_service.py
safe_relay_service/relay/tests/test_views_v2.py
safe_relay_service/version.py

- Don't return empty safe creation estimations

Set version 3.4.1

---

requirements.txt
safe_relay_service/relay/models.py
safe_relay_service/relay/serializers.py
safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tests/test_transaction_service.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/relay/urls.py
safe_relay_service/relay/views.py
safe_relay_service/tokens/models.py

Implement tx estimation for all gas tokens

---

config/urls.py
requirements.txt
safe_relay_service/relay/admin.py
safe_relay_service/relay/models.py
safe_relay_service/relay/serializers.py
safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tests/test_transaction_service.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/relay/urls.py
safe_relay_service/relay/views.py
safe_relay_service/tokens/models.py
safe_relay_service/version.py

- Implement tx estimation for all gas tokens
- Optimize Safe balance calculation

 Set version 3.5.0

---

safe_relay_service/relay/models.py
safe_relay_service/version.py

- Fix ether balance calculation: Delegate calls should not compute for balance calculation

 Set version 3.5.1

---

safe_relay_service/relay/models.py
safe_relay_service/version.py

Set version v3.5.4

---

safe_relay_service/gas_station/gas_station.py
safe_relay_service/gas_station/tests/factories.py
safe_relay_service/gas_station/tests/test_gas_station.py
safe_relay_service/gas_station/tests/test_models.py
safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tests/relay_test_case.py
safe_relay_service/relay/tests/test_funding_service.py
safe_relay_service/relay/tests/test_safe_creation_service.py
safe_relay_service/relay/tests/test_transaction_service.py

- Refactor gas station, services and tests
- Closes #101

Use standard gas price instead of fast

---

safe_relay_service/relay/serializers.py
safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/tasks.py
safe_relay_service/relay/tests/test_views_v2.py
safe_relay_service/relay/urls_v2.py
safe_relay_service/relay/views_v2.py
safe_relay_service/version.py

- Fix tasks redis locking
- Format ints as strings for tx estimation #108 
- Increase soft time limit for indexing task
- Fix creating of SafeTxStatus

Set version 3.5.10

---

safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/tokens/models.py
safe_relay_service/tokens/tests/test_models.py

- Refactor multiple token estimations for creation of Safes
- Refactor multiple token estimations for txs
- Closes #119

Make multiple token estimation faster

---

requirements.txt
safe_relay_service/relay/models.py
safe_relay_service/relay/repositories/redis_repository.py
safe_relay_service/relay/services/safe_creation_service.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/tokens/models.py
safe_relay_service/tokens/tests/test_models.py
safe_relay_service/version.py

- Make multiple token estimation faster
- Just use `pending` state for nonce calculation

Set version 3.5.14

---

.github/bug_report.md
.github/feature_request.md

Add feature and bug templates

---

.github/bug_report.md
.github/feature_request.md
safe_relay_service/relay/admin.py
safe_relay_service/relay/views.py
safe_relay_service/tokens/tests/test_models.py
safe_relay_service/version.py

- Add feature and bug templates (#128)
- Fix problem paginating Safes

Set version v3.5.15

---

safe_relay_service/relay/models.py
safe_relay_service/relay/serializers.py
safe_relay_service/relay/services/stats_service.py
safe_relay_service/relay/tests/test_stats_service.py
safe_relay_service/relay/tests/test_views.py
safe_relay_service/relay/views.py
safe_relay_service/version.py

- Fix calculation of token balances. Now everything is retrieved from blockchain #125
- Fix exception handling for tx endpoint
- Fix typo: rename `median` -> `average` on stats endpoint
- Rename `value` -> `balance` in token endpoint

Set version 3.6.3

---

docker/web/run_web.sh
safe_relay_service/relay/management/commands/fix_safe_tx_hash.py
safe_relay_service/relay/management/commands/test_relay_server.py
safe_relay_service/relay/models.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tasks.py
safe_relay_service/tokens/tests/test_exchanges.py
safe_relay_service/version.py

- Fix typo storing `tx_hash` as `safe_tx_hash`

Set version 3.8.1

---

requirements.txt
safe_relay_service/version.py

Set version 3.8.6

---

safe_relay_service/relay/services/transaction_service.py
safe_relay_service/version.py

Set version 3.8.7

---

docker/web/celery/worker/run.sh
docker/web/run_web.sh
requirements-test.txt
requirements.txt
safe_relay_service/relay/management/commands/resend_txs.py
safe_relay_service/relay/models.py
safe_relay_service/relay/services/transaction_service.py
safe_relay_service/relay/tests/test_resend_txs.py
safe_relay_service/version.py

- Add command to resend pending txs

Set version 3.8.8

---

docker/nginx/safe_service.conf
docker/web/celery/scheduler/run.sh
docker/web/celery/worker/run.sh
docker/web/run_web.sh
requirements-test.txt
requirements.txt
safe_relay_service/relay/tests/test_views.py
safe_relay_service/relay/views_v2.py
safe_relay_service/relay/views_v3.py
safe_relay_service/version.py

- Add a new fix for gas problems #200

Set version 3.8.9

---

.github/workflows/python.yml
scripts/autodeploy.sh

- Removed Dockerhub autodeploy weebhooks
- Added new step for the autodeploy request after the image is built
- Added auth to autodeploy service, now is more secure the deployment of new versions.
- Added nginx auth script

Add autodeploy github actions step with nginx auth script

---

scripts/deploy_docker.sh

- Changes `gnosispm` to `safeglobal` when building and pushing Docker images

Update org in docker images

---

requirements.txt

Add hiredis
